<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'slug' => 'sumatra-gayo-anaerobic-honey',
                'name_id' => 'Sumatra Gayo Anaerobic Honey',
                'name_en' => 'Sumatra Gayo Anaerobic Honey',
                'origin_id' => 'Indonesia, Dataran Tinggi Takengon',
                'origin_en' => 'Indonesia, Takengon Highlands',
                'roast_level' => 'Medium',
                'price' => 224000,
                'description_id' => 'Sebuah mahakarya dari Dataran Tinggi Gayo. Bersumber dari perkebunan organik teduh pada ketinggian 1.600 mdpl, lot mikro ini melalui fermentasi anaerobik selama 72 jam dalam tangki kedap udara, diikuti oleh pemrosesan honey. Menghasilkan body yang tebal dan bersirof dengan rasa buah tropis yang intens serta rempah halus.',
                'description_en' => 'A masterpiece from the Gayo Highlands. Sourced from organic shade-grown estates at 1,600 masl, this micro-lot undergoes 72 hours of anaerobic fermentation in airtight tanks, followed by honey processing. Delivers a thick, syrupy mouthfeel with intense tropical fruits and delicate spices.',
                'image' => 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?q=80&w=400',
                'rating' => 5.0,
                'process_id' => 'Anaerobic Honey',
                'process_en' => 'Anaerobic Honey',
                'elevation' => '1.600 mdpl',
                'sca_score' => 90.5,
                'stock_status' => 'Limited',
                'moisture' => '11.1%',
                'fob_price_range' => '$12.50 - $14.50 / kg',
                'available_lots_id' => '15 Karung (900 kg)',
                'available_lots_en' => '15 Bags (900 kg)',
                'defect_count_id' => 'SCA Grade 1 (0 primary, < 3 secondary)',
                'defect_count_en' => 'SCA Grade 1 (0 primary, < 3 secondary)',
                'bag_type_id' => 'Karung Rami 60kg dengan GrainPro',
                'bag_type_en' => '60kg Jute Bag with GrainPro Liner',
                'is_featured' => true,
                'sort_order' => 1,
                'flavor_notes_id' => ['Beludru Merah', 'Markisa', 'Kayu Aras Manis', 'Gula Aren'],
                'flavor_notes_en' => ['Red Velvet', 'Passion Fruit', 'Sweet Cedar', 'Palm Sugar'],
            ],
            [
                'slug' => 'bali-kintamani-carbonic-maceration',
                'name_id' => 'Bali Kintamani Carbonic Maceration',
                'name_en' => 'Bali Kintamani Carbonic Maceration',
                'origin_id' => 'Indonesia, Lereng Vulkanik Gunung Batur',
                'origin_en' => 'Indonesia, Volcanic Slopes of Mount Batur',
                'roast_level' => 'Light',
                'price' => 256000,
                'description_id' => 'Ditanam di tanah kaya mineral di Gunung Batur, lot single-estate varietas Bourbon & Typica ini menggunakan maserasi karbonik tingkat lanjut (tangki yang dialiri CO2) untuk menciptakan kemanisan buah yang cerah dan keasaman laktat yang kompleks. Hasil seduhan yang sangat bersih, sempurna untuk penyangrai kopi gelombang ketiga.',
                'description_en' => 'Grown on mineral-rich volcanic soil on Mount Batur, this single-estate Bourbon & Typica lot uses advanced carbonic maceration (CO2 flushed tanks) to create sparkling fruit sweetness and complex lactic acidity. Extremely clean cup, perfect for third-wave specialty roasters.',
                'image' => 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=400',
                'rating' => 4.9,
                'process_id' => 'Carbonic Maceration',
                'process_en' => 'Carbonic Maceration',
                'elevation' => '1.550 mdpl',
                'sca_score' => 91.0,
                'stock_status' => 'Available',
                'moisture' => '11.3%',
                'fob_price_range' => '$14.00 - $16.50 / kg',
                'available_lots_id' => '24 Karung (1.440 kg)',
                'available_lots_en' => '24 Bags (1,440 kg)',
                'defect_count_id' => 'Tanpa Cacat Primer (Zero Defects)',
                'defect_count_en' => 'Zero Primary Defects',
                'bag_type_id' => 'Kotak Vakum Hermetis 30kg',
                'bag_type_en' => '30kg Airtight Vacuum Box',
                'is_featured' => true,
                'sort_order' => 2,
                'flavor_notes_id' => ['Bunga Jeruk', 'Selai Stroberi', 'Nibs Kakao', 'Krim Mangga'],
                'flavor_notes_en' => ['Orange Blossom', 'Strawberry Jam', 'Cacao Nibs', 'Mango Cream'],
            ],
            [
                'slug' => 'java-preanger-washed-estate',
                'name_id' => 'Java Preanger Washed Estate',
                'name_en' => 'Java Preanger Washed Estate',
                'origin_id' => 'Indonesia, Kawasan Vulkanik Jawa Barat',
                'origin_en' => 'Indonesia, West Java Volcanic Region',
                'roast_level' => 'Medium',
                'price' => 176000,
                'description_id' => 'Cita rasa historis secangkir kopi "Aie". Diperoleh dari terasering vulkanik tertua di Jawa Barat, Java Preanger diproses secara double-washed untuk memberikan kejernihan rasa yang luar biasa, rasa di mulut yang menyerupai teh, dan aroma sitrus yang sangat lembut. Lot yang sangat stabil untuk blending kelas atas maupun espresso single-origin.',
                'description_en' => 'The historic taste of a cup of "Aie". Sourced from the oldest volcanic terraces in West Java, Java Preanger is double-washed to provide outstanding flavor clarity, a tea-like body, and very refined citrus undertones. A highly stable lot for premium blending or single-origin espresso.',
                'image' => 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?q=80&w=400',
                'rating' => 4.8,
                'process_id' => 'Double Washed',
                'process_en' => 'Double Washed',
                'elevation' => '1.650 mdpl',
                'sca_score' => 88.5,
                'stock_status' => 'Available',
                'moisture' => '10.9%',
                'fob_price_range' => '$9.50 - $11.50 / kg',
                'available_lots_id' => '40 Karung (2.400 kg)',
                'available_lots_en' => '40 Bags (2,400 kg)',
                'defect_count_id' => 'SCA Grade 1 (Ekspor Premium)',
                'defect_count_en' => 'SCA Grade 1 (Premium Export)',
                'bag_type_id' => 'Karung Rami 60kg dengan GrainPro',
                'bag_type_en' => '60kg Jute Bag with GrainPro Liner',
                'is_featured' => true,
                'sort_order' => 3,
                'flavor_notes_id' => ['Teh Melati', 'Serai', 'Karamel Manis', 'Kranberi'],
                'flavor_notes_en' => ['Jasmine Tea', 'Lemongrass', 'Sweet Caramel', 'Cranberry'],
            ],
            [
                'slug' => 'sulawesi-toraja-sapan-grade-1',
                'name_id' => 'Sulawesi Toraja Sapan Grade 1',
                'name_en' => 'Sulawesi Toraja Sapan Grade 1',
                'origin_id' => 'Indonesia, Lereng Gunung Sesean',
                'origin_en' => 'Indonesia, Slopes of Mount Sesean',
                'roast_level' => 'Dark',
                'price' => 192000,
                'description_id' => 'Lot warisan klasik dari Sulawesi Selatan. Diproduksi menggunakan pengupasan kering mikro-lot yang teliti. Kopi Sapan terkenal dengan bodinya yang tebal dan lembut, keasaman rendah, serta sentuhan kakao gelap yang pekat dan kayu cendana yang harum. Sangat direkomendasikan untuk portofolio sangrai gelap premium.',
                'description_en' => 'A classic heritage lot from South Sulawesi. Produced using meticulous dry hulling for micro-lots. Sapan coffee is renowned for its thick and creamy body, low acidity, and deep dark chocolate notes with fragrant sandalwood. Highly recommended for premium dark roast portfolios.',
                'image' => 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?q=80&w=400',
                'rating' => 4.7,
                'process_id' => 'Wet Hulled (Giling Basah)',
                'process_en' => 'Wet Hulled (Giling Basah)',
                'elevation' => '1.700 mdpl',
                'sca_score' => 88.0,
                'stock_status' => 'Available',
                'moisture' => '11.5%',
                'fob_price_range' => '$10.00 - $12.50 / kg',
                'available_lots_id' => '18 Karung (1.080 kg)',
                'available_lots_en' => '18 Bags (1,080 kg)',
                'defect_count_id' => 'Ekspor Spesial Pilihan Tiga Kali (Triple-Picked)',
                'defect_count_en' => 'Premium Triple-Picked Export',
                'bag_type_id' => 'Karung Rami 60kg dengan GrainPro',
                'bag_type_en' => '60kg Jute Bag with GrainPro Liner',
                'is_featured' => false,
                'sort_order' => 4,
                'flavor_notes_id' => ['Truf Cokelat', 'Tetes Tebu', 'Kayu Cendana', 'Plum Matang'],
                'flavor_notes_en' => ['Chocolate Truffle', 'Molasses', 'Sandalwood', 'Ripe Plum'],
            ],
            [
                'slug' => 'panama-geisha-esmeralda-reserve',
                'name_id' => 'Panama Geisha Esmeralda Reserve',
                'name_en' => 'Panama Geisha Esmeralda Reserve',
                'origin_id' => 'Panama, Lembah Mikro Jaramillo',
                'origin_en' => 'Panama, Jaramillo Micro Valley',
                'roast_level' => 'Light',
                'price' => 832000,
                'description_id' => 'Standar internasional tertinggi kopi mewah. Ditanam di ketinggian ekstrem 1.800 mdpl di bawah naungan kabut pegunungan, lot Geisha ini mewakili intensitas aroma floral yang murni, bergamot yang elegan, dan body jeruk mandarin yang manis. Dinilai oleh tim Q-grader kami dengan skor luar biasa 93 poin.',
                'description_en' => 'The highest international standard of luxury coffee. Grown at an extreme altitude of 1,800 masl under the shade of mountain mists, this Geisha lot represents pristine floral intensity, elegant bergamot, and a sweet mandarin orange body. Graded at an extraordinary 93 points by our Q-grader team.',
                'image' => 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=400',
                'rating' => 5.0,
                'process_id' => 'Washed',
                'process_en' => 'Washed',
                'elevation' => '1.800 mdpl',
                'sca_score' => 93.0,
                'stock_status' => 'Limited',
                'moisture' => '10.6%',
                'fob_price_range' => '$48.00 - $55.00 / kg',
                'available_lots_id' => '6 Karung (360 kg)',
                'available_lots_en' => '6 Bags (360 kg)',
                'defect_count_id' => 'Spesial Murni Tanpa Cela (Pristine)',
                'defect_count_en' => 'Pristine Specialty Grade',
                'bag_type_id' => 'Kotak Vakum Hermetis 30kg',
                'bag_type_en' => '30kg Airtight Vacuum Box',
                'is_featured' => false,
                'sort_order' => 5,
                'flavor_notes_id' => ['Bunga Bergamot', 'Persik Putih', 'Teh Melati', 'Jeruk Mandarin'],
                'flavor_notes_en' => ['Bergamot Flower', 'White Peach', 'Jasmine Tea', 'Mandarin Orange'],
            ],
            [
                'slug' => 'sidama-highlands-heirloom',
                'name_id' => 'Sidama Highlands Heirloom',
                'name_en' => 'Sidama Highlands Heirloom',
                'origin_id' => 'Etiopia, Wilayah Yirgacheffe',
                'origin_en' => 'Ethiopia, Yirgacheffe Region',
                'roast_level' => 'Light',
                'price' => 208000,
                'description_id' => 'Lot heirloom alami yang bersumber dari keluarga petani kecil di dataran tinggi Yirgacheffe. Dikeringkan di bawah sinar matahari langsung di atas meja jemur khas Afrika, kopi ini menunjukkan aroma selai blueberry yang meledak-ledak dan kejernihan bergamot yang berkilau.',
                'description_en' => 'A sun-dried natural heirloom lot sourced from smallholder families in the high plateaus of Yirgacheffe. Dried under direct sunlight on African raised beds, this coffee shows explosive blueberry jam aromas and brilliant bergamot clarity.',
                'image' => 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?q=80&w=400',
                'rating' => 4.9,
                'process_id' => 'Natural Sun-dried',
                'process_en' => 'Natural Sun-dried',
                'elevation' => '2.000 mdpl',
                'sca_score' => 89.5,
                'stock_status' => 'Available',
                'moisture' => '11.2%',
                'fob_price_range' => '$11.50 - $13.50 / kg',
                'available_lots_id' => '30 Karung (1.800 kg)',
                'available_lots_en' => '30 Bags (1,800 kg)',
                'defect_count_id' => 'SCA Grade 1 Specialty',
                'defect_count_en' => 'SCA Grade 1 Specialty',
                'bag_type_id' => 'Karung Rami 60kg dengan GrainPro',
                'bag_type_en' => '60kg Jute Bag with GrainPro Liner',
                'is_featured' => false,
                'sort_order' => 6,
                'flavor_notes_id' => ['Selai Blueberry', 'Lavender', 'Kulit Lemon', 'Teh Earl Grey'],
                'flavor_notes_en' => ['Blueberry Jam', 'Lavender', 'Lemon Zest', 'Earl Grey Tea'],
            ],
            [
                'slug' => 'andean-volcanic-washed',
                'name_id' => 'Andean Volcanic Washed',
                'name_en' => 'Andean Volcanic Washed',
                'origin_id' => 'Kolombia, Terasering Huila',
                'origin_en' => 'Colombia, Huila Terraces',
                'roast_level' => 'Medium',
                'price' => 160000,
                'description_id' => 'Lot komersial dengan hasil tinggi dan keseimbangan rasa luar biasa dari Huila. Ditanam di lereng tanah liat vulkanik yang kaya nutrisi, memberikan cangkir kopi yang sangat manis, body penuh, dengan aroma cokelat yang kuat dan keasaman buah merah yang menyenangkan. Sangat ideal untuk roastery bervolume tinggi.',
                'description_en' => 'A high-yielding commercial lot with exceptional balance from Huila. Grown on volcanic clay soils rich in nutrients, providing a sweet, full-bodied cup with robust chocolate aromas and a pleasant red fruit acidity. Ideal for high-volume roasteries.',
                'image' => 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?q=80&w=400',
                'rating' => 4.8,
                'process_id' => 'Fully Washed',
                'process_en' => 'Fully Washed',
                'elevation' => '1.600 mdpl',
                'sca_score' => 88.0,
                'stock_status' => 'Available',
                'moisture' => '11.0%',
                'fob_price_range' => '$8.50 - $10.50 / kg',
                'available_lots_id' => '50 Karung (3.000 kg)',
                'available_lots_en' => '50 Bags (3,000 kg)',
                'defect_count_id' => 'SCA Standard Export Grade 1',
                'defect_count_en' => 'SCA Standard Export Grade 1',
                'bag_type_id' => 'Karung Rami 60kg dengan GrainPro',
                'bag_type_en' => '60kg Jute Bag with GrainPro Liner',
                'is_featured' => false,
                'sort_order' => 7,
                'flavor_notes_id' => ['Cokelat Susu', 'Almond Panggang', 'Gula Merah Panela', 'Kismis Merah'],
                'flavor_notes_en' => ['Milk Chocolate', 'Roasted Almond', 'Panela Brown Sugar', 'Red Currant'],
            ],
            [
                'slug' => 'ecuador-el-maputo-anaerobic',
                'name_id' => 'Ecuador El Maputo Anaerobic',
                'name_en' => 'Ecuador El Maputo Anaerobic',
                'origin_id' => 'Ekuador, Provinsi Pichincha',
                'origin_en' => 'Ecuador, Pichincha Province',
                'roast_level' => 'Light',
                'price' => 352000,
                'description_id' => 'Lot fermentasi ganda anaerobik dari hutan awan tinggi Pichincha. Menyajikan ledakan minyak buah tropis yang intens dan berair, rasa manis mangga yang pekat, dan ketahanan rasa kakao mentah di langit-langit mulut. Lot langka kelas kompetisi.',
                'description_en' => 'A double anaerobic natural lot from the high cloud forests of Pichincha. Delivers an intense explosion of tropical fruit oils, rich mango sweetness, and lingering raw cacao on the palate. A rare competition-grade lot.',
                'image' => 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?q=80&w=400',
                'rating' => 4.9,
                'process_id' => 'Double Anaerobic Natural',
                'process_en' => 'Double Anaerobic Natural',
                'elevation' => '1.750 mdpl',
                'sca_score' => 90.5,
                'stock_status' => 'Sold Out',
                'moisture' => '11.4%',
                'fob_price_range' => '$20.00 - $24.00 / kg',
                'available_lots_id' => '0 Karung (Teralokasi)',
                'available_lots_en' => '0 Bags (Allocated)',
                'defect_count_id' => 'SCA Grade 1 Specialty',
                'defect_count_en' => 'SCA Grade 1 Specialty',
                'bag_type_id' => 'Kotak Vakum Hermetis 30kg',
                'bag_type_en' => '30kg Airtight Vacuum Box',
                'is_featured' => false,
                'sort_order' => 8,
                'flavor_notes_id' => ['Minyak Markisa', 'Pure Mangga', 'Beri Liar', 'Nibs Kakao'],
                'flavor_notes_en' => ['Passion Fruit Oil', 'Mango Puree', 'Wild Berries', 'Cacao Nibs'],
            ],
        ];

        foreach ($products as $data) {
            $flavorNotesId = $data['flavor_notes_id'];
            $flavorNotesEn = $data['flavor_notes_en'];
            unset($data['flavor_notes_id'], $data['flavor_notes_en']);

            $product = Product::create($data);

            foreach ($flavorNotesId as $i => $note) {
                $product->flavorNotes()->create([
                    'locale' => 'id',
                    'note' => $note,
                    'sort_order' => $i,
                ]);
            }

            foreach ($flavorNotesEn as $i => $note) {
                $product->flavorNotes()->create([
                    'locale' => 'en',
                    'note' => $note,
                    'sort_order' => $i,
                ]);
            }
        }
    }
}
